from typing import Protocol

from stockflow.application.dto.supplier_input import SupplierInput
from stockflow.domain.entities.supplier import Supplier


class SupplierRepository(Protocol):
    def list_all(self) -> tuple[Supplier, ...]: ...

    def search(self, query: str) -> tuple[Supplier, ...]: ...

    def find_by_document(self, document: str) -> Supplier | None: ...

    def get(self, supplier_id: str) -> Supplier | None: ...

    def exists(self, supplier_id: str) -> bool: ...

    def create(self, data: SupplierInput) -> Supplier: ...

    def update(self, supplier_id: str, data: SupplierInput) -> Supplier: ...

    def set_active(self, supplier_id: str, active: bool) -> None: ...

    def next_id(self) -> str | None: ...
