from PySide6.QtCore import Qt
from PySide6.QtWidgets import QFrame, QHBoxLayout, QLabel, QProgressBar, QPushButton, QVBoxLayout, QWidget


class ProductCard(QPushButton):
    def __init__(self, product, stock_maximum):
        super().__init__()
        self.setObjectName('productCard')
        self.setCursor(Qt.PointingHandCursor)
        self.setFixedHeight(190)
        self.setMinimumWidth(270)
        self.setAccessibleName(f'Ver detalhes de {product.name}')
        self.setToolTip('Clique para ver os detalhes do produto')
        layout = QVBoxLayout(self)
        layout.setContentsMargins(20, 18, 20, 18)
        layout.setSpacing(10)
        top = QHBoxLayout()
        code = QLabel(product.code)
        code.setObjectName('productCode')
        top.addWidget(code)
        top.addStretch()
        status_text = product.stock_status if product.active else 'Inativo'
        status = QLabel(status_text)
        colors = {
            'Normal': ('#047857', '#ECFDF5', '#A7F3D0'),
            'Baixo': ('#B45309', '#FFFBEB', '#FDE68A'),
            'Crítico': ('#DC2626', '#FEF2F2', '#FECACA'),
        }
        foreground, background, border = colors.get(status_text, ('#475569', '#F1F5F9', '#CBD5E1'))
        status.setStyleSheet(f'color: {foreground}; background: {background}; border: 1px solid {border}; border-radius: 9px; padding: 2px 9px; font-size: 11px;')
        top.addWidget(status)
        layout.addLayout(top)
        name = QLabel(product.name)
        name.setWordWrap(True)
        name.setObjectName('productName')
        layout.addWidget(name)
        category = QLabel(product.category)
        category.setObjectName('productCategory')
        layout.addWidget(category, 0, Qt.AlignLeft)
        layout.addStretch()
        divider = QFrame()
        divider.setFixedHeight(1)
        divider.setObjectName('productDivider')
        layout.addWidget(divider)
        bottom = QHBoxLayout()
        stock_layout = QVBoxLayout()
        stock_layout.setSpacing(4)
        stock_label = QLabel('Em estoque')
        stock_label.setObjectName('productCaption')
        stock_layout.addWidget(stock_label)
        stock_row = QHBoxLayout()
        bar = QProgressBar()
        bar.setRange(0, stock_maximum)
        bar.setValue(int(product.stock))
        bar.setTextVisible(False)
        bar.setFixedSize(74, 6)
        color = '#FF6376' if product.stock_status == 'Crítico' else '#FBBF24' if product.stock_status == 'Baixo' else '#3482FF'
        bar.setStyleSheet(f'QProgressBar {{ background: #EFF6FF; border: none; border-radius: 3px; }} QProgressBar::chunk {{ background: {color}; border-radius: 3px; }}')
        stock_value = QLabel(product.stock)
        stock_value.setObjectName('productCaption')
        stock_row.addWidget(bar)
        stock_row.addWidget(stock_value)
        stock_row.addStretch()
        stock_layout.addLayout(stock_row)
        bottom.addLayout(stock_layout)
        bottom.addStretch()
        price_layout = QVBoxLayout()
        price_layout.setSpacing(2)
        caption = QLabel('Preço')
        caption.setObjectName('productCaption')
        caption.setAlignment(Qt.AlignRight)
        price = QLabel(product.sale_price)
        price.setObjectName('productPrice')
        price.setAlignment(Qt.AlignRight)
        price_layout.addWidget(caption)
        price_layout.addWidget(price)
        bottom.addLayout(price_layout)
        layout.addLayout(bottom)
        for child in self.findChildren(QWidget):
            child.setAttribute(Qt.WA_TransparentForMouseEvents)
        self.setToolTip('Ver detalhes · A barra compara o estoque com o maior estoque do catálogo.')
